### ISSUE TITLE
Specify module name in podspec

### ISSUE THREAD

**Issue by ashfurrow** [artsy/Artsy-OSSUIFonts#1]
Probably in a branch, since swift pods are still in beta. 

I'd assign this issue to myself, but I'm not listed as a collaborator on this repo cough cough.

**Comment by orta** [comment]
Podspec mr furrow

**Comment by ashfurrow** [comment]
Ah, thanks.

**Comment by orta** [comment]
Added the mobile team to this repo, and added authentication :+1:
