### ISSUE TITLE
Font Family typo? 

### ISSUE THREAD

**Issue by y310** [artsy/Artsy-OSSUIFonts#11]
With the latest master artsy/eigen, I could launch the app. But after onboarding process, when the app opens a home screen, the app showed following error.
![image](https://cloud.githubusercontent.com/assets/188655/24273283/ba4aa4fa-1021-11e7-9a3f-48f3b473bfad.png)

I checked `texgyreadventor-regular.ttf` in this repository and found that Font Family name is `Avante Gard Gothic ITCW01Dm` instead of `Avant Garde Gothic ITCW01Dm`.
I guess this is typo which was introduced when it was tweaked to have same name with closed source version.
Sorry in advance if I'm wrong 🙇 

```sh
% mdls texgyreadventor-regular.ttf
_kMDItemOwnerUserID            = 501
com_apple_ats_name_family      = (
    "Avante Gard Gothic ITCW01Dm"
)
com_apple_ats_name_fond        = (
    AvantGardeGothicITCW01Dm
)
com_apple_ats_name_full        = (
    "Avant Gard Gothic ITCW01Dm"
)
com_apple_ats_name_postscript  = (
    AvantGardeGothicITCW01Dm
)
com_apple_ats_name_style       = (
    Regular
)
com_apple_ats_names            = (
    "",
    "Avant Gard Gothic ITCW01Dm",
    AvantGardeGothicITCW01Dm,
    "Avante Gard Gothic ITCW01Dm",
    "Copyright (URW)++, copyright 1999 by (URW)++ Design & Development; Cyrillic glyphs added by Valek Filippov, copyright 2001-2002; Vietnamese characters were added by Han The Thanh; copyright 2006, 2008 for TeX Gyre extensions by B. Jackowski and J.M. Nowacki (on behalf of TeX users groups). This work is released under the GUST Font License --  see http://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt for details.",
    Regular,
    "Version 1.104;PS 1.104;hotconv 1.0.49;makeotf.lib2.0.14853 - artsy"
)
(snip)
```

**Comment by orta** [comment]
Hah, yeah, I couldn't copy & paste into the font editor as it was some UNIX GUI tool - this is a mistake on my part

**Comment by orta** [comment]
Alright, that's it updated and PR sent to eigne/emission - thanks!
